name: Feature Request
title: 'Sweep: '
description: Write something like "Write an api endpoint that does "..." in the "..." file"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic
if user_is_ai:
  skip_actions = True
if user_is_ai:
  skip_actions = True